FROM registry.k8s.cloud.statcan.ca/stcdatascience/artemis/centos7-py36-arrow:v1

MAINTAINER Dominic Parent <dominic.parent@canada.ca>

RUN pip install --upgrade pip
RUN pip install setuptools cython packaging protobuf matplotlib
