# Copyright © Her Majesty the Queen in Right of Canada, as represented
# by the Minister of Statistics Canada, 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
package:
    name: artemis
    version: 0.5.0

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - gcc_linux-64 >=5.1
        - gxx_linux-64 >=5.1
        - cmake >=3.2
        - make  
        - python=3.7.3
        - setuptools
    run:
        - python=3.7.3
        - pip  # keep conda happy  
        - pkg-config
        - numpy 
        - scipy 
        - pandas 
        - matplotlib 
        - cython 
        - cloudpickle 
        - hypothesis 
        - packaging 
        - sas7bdat 
        - protobuf 
        - dask>=1.2.2
        - pygraphviz
        - matplotlib
        - mypy
        - pyarrow=0.14.1
        - simplekv
        - xlrd
        - faker
        - coverage
test:
    imports:
        - artemis
    commands:
        - python -m unittest examples/example_product.py

about:
    summary: 'Artemis Analytics Platform'
