package:
    name: artemis
    version: 0.5.0

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - gcc_linux-64
        - gxx_linux-64
        - cmake
        - make  
        - python=3.7
        - setuptools
    run:
        - python=3.7
        - pip  # keep conda happy  
        - pkg-config
        - numpy 
        - scipy 
        - pandas 
        - matplotlib 
        - cython 
        - cloudpickle 
        - hypothesis 
        - packaging 
        - sas7bdat 
        - protobuf 
        - dask>=1.2.2
        - pygraphviz
        - matplotlib
        - mypy
        - pyarrow>=0.14
        - simplekv
        - xlrd
        - faker
        - coverage
test:
    imports:
        - artemis
    commands:
        - python -m unittest examples/test_artemis.py

about:
    summary: 'Artemis Analytics Platform'
